services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    image: littlepay:dev
    entrypoint: sleep infinity
    volumes:
      - .:/home/calitp/app
      - ./.config:/home/calitp/.littlepay
